RI_Portal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Professor/',include('professor.urls',namespace='Professor')),
    url(r'^student/',include('student.urls',namespace='student')),
  url(r'^home/',include('home.urls',namespace='home'))
]

#url(r'^$',TemplateView.as_view(template_name='pms_index.html')), url(r'^home/',include('home.urls'))

home/urls.py
from django.conf.urls import url
from student import views

app_name='home'
urlpatterns = [
   
    url(r'^$', views.studentlogin, name='home'),
    url(r'^home/',views.studentlogin, name='home'),
]

professor/urls.py
from django.conf.urls import url
from  .import views
app_name='professor'
urlpatterns = [
    url(r'signup', views.post_list, name='signup_page'),
    url(r'login', views.view_home, name='login_page'),
    url(r'edit', views.view_edit, name='home_page'),
    url(r'verify',views.verify,name='verify_page'),
    url(r'userc/(?P<username>[A-Za-z_0-9]+)/$', views.profile, name='profile'),
    url(r'projectreqs',views.projectreqs,name='project_requirements'),
    url(r'change_password', views.change_password,1name='passchg'),
    url(r'changed', views.successfull_change,name='passchgsucc'),
    url(r'listproject',views.listproject,name='listproject'),
    url(r'project/(?P<projectid>[0-9]+)/',views.projectdesc,name='projectdesc'),
    url(r'applied_msg/', views.projectapplied, name='projectapplied'),
    url(r'student_list/(?P<projectid>[0-9]+)/', views.view_student_list, name='studlist'),
    url(r'taken_name/', views.already_taken, name="takenc"),
    url(r'offered/(?P<userid>[A-Za-z_0-9]+)/$', views.offered, name="takenc"),

]

student/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name='student'
urlpatterns = [
    #home/ or / or student/
    url(r'student_login/$', views.studentlogin, name='student_off'),
    url(r'auth/$', views.auth_view ,name='auth'),
    url(r'edit_details/$', views.view_edit ,name='edit_page'),
    url(r'logout/$',views.logout,name='logout'),
    url(r'users/(?P<username>[A-Za-z_0-9]+)/$', views.profile, name='profile'),
#    url(r'loggedin/$',views.loggedin,name='loggedin'),
  #  url(r'invalid/$',views.invalid_login,name='invalid'),
    url(r'^home/',views.studentlogin, name='student'),
    url(r'^$', views.studentlogin, name='student'),
 #register new student
    url(r'register/$', views.studentregistration, name='student_register'),
    url(r'listproject/',views.listproject,name='list_project'),
    url(r'changed/', views.successfull_change,name='passchgsucc'),
    url(r'change_password/$', views.change_password, name='passchg'),
    url(r'offer_letter/', views.get_offer, name='offer'),
    url(r'success/',views.update_details,name="update"),
    url(r'taken_name/',views.already_taken,name="taken"),
    url(r'profile/(?P<username>[A-Za-z_0-9]+)/$', views.view_stud_details, name="stud_details"),
    url(r'download/', views.download, name="download"),
    url(r'resume/(?P<username>[A-Za-z_0-9]+)/$', views.resumed, name="resumed"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

professor/models.py
from django.db import models
from django.core.validators import RegexValidator
from django import forms

# Create your models here.
class Register(models.Model):
    c_name=models.CharField(max_length=20,blank=True,null=True,unique=True)
    c_professor_name=models.CharField(max_length=20,blank=True,null=True)
    c_details=models.TextField(blank=True)
    c_verified=models.BooleanField(default=False,blank=True)
    c_verification=models.IntegerField(default=0,blank=True)
  
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    c_contact = models.CharField(validators=[phone_regex], blank=True,max_length=15) 
    c_email = models.EmailField(blank=True)
    c_password=models.CharField(max_length=30,blank=True)
    c_confirm_password=models.CharField(max_length=30,blank=True)
    c_ppt = models.FileField(upload_to="documents/", blank=True)
  
    def __str__(self):
        return str(self.c_name)

class Edit_Details(models.Model):
    register  = models.ForeignKey(Register, on_delete=models.CASCADE)
    c_email = models.EmailField(blank=True)
    #c_email = models.ForeignKey(Register, on_delete=models.CASCADE)
    c_ppt = models.FileField(upload_to="documents/",blank=True)
    def __str__(self):
        return str(self.c_name)
class project_desc(models.Model):
    COURSE = (
        ('BTECH', 'bachelors'),
        ('MTECH', 'masters'),
        ('PHD', 'philospher'),
    )
    BRANCH = (
        ('CS', 'computer_science'),
        ('ME', 'mechanical'),
        ('EE', 'electrical'),
    )
    register = models.ForeignKey('Register', on_delete=models.CASCADE,null=True)
    c_position = models.CharField(max_length=30,blank=True,null=True)
    list_of_student=models.CharField(max_length=500,blank=True,null=True)
   
    c_description=models.CharField(max_length=500,null=True)
    date_published = models.DateField(null=True)
    date_expiry=models.DateField(null=True)
    c_ctc_offered = models.DecimalField(decimal_places=2, max_digits=8, blank=True,null=True)
    c_branch = models.CharField(max_length=10, choices=BRANCH, default='CS')  
    c_course = models.CharField(max_length=5, choices=COURSE, default='BTECH') 
    def __str__(self):
        return str(self.c_position)

professor/forms.py
from django import forms
from .models import Register,Edit_Details,project_desc
from django.contrib.auth.forms import AuthenticationForm
class Postform(forms.ModelForm):
    class Meta:
        model=Register
        widgets = {
            'c_password': forms.PasswordInput(),
            'c_confirm_password' : forms.PasswordInput(),
        }
        fields=['c_name','c_professor_name','c_password','c_contact','c_email','c_details']
class Loginform(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'}))
    def clean(self):
        pass

class EditForm(forms.ModelForm):
    class Meta :
        model = Register
        fields=['c_details','c_email','c_ppt']

class projectReqs(forms.ModelForm):
    class Meta:
        model = project_desc
        widgets = {
            'date_expiry': forms.TextInput(attrs={'placeholder': 'DD/MM/YYYY'}),
            'date_published': forms.TextInput(attrs={'placeholder': 'DD/MM/YYYY'}),
        }
        fields=['c_position','c_description','c_stipend_offered','c_branch','c_course','date_published','date_expiry']

class ChangePass(forms.ModelForm):
    class Meta:
        fields=['c_oldpassword','c_newpassword','c_confirm_password']

professor/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from .forms import Postform
from .forms import Loginform,EditForm,projectReqs
from .models import Register,project_desc
from django.contrib.auth.decorators import login_required
import random
from student.models import Notifications,Appliedproject,StudentDB
from django.core.mail import send_mail
# Create your views here.
def post_list(request):
    status = 200
    print('hello')
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = Postform(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            instance=form.save(commit=False)
            #print(instance.c_password)
            #print(instance.c_confirm_password)
            instance.c_verification = random.randint(1,1000)
            instance.save()

            #form=Postform()
            #return render(request, 'Professor/tempform.html', {'form': form}, status=status)
            #form.save()
            '''send_mail(
                'Verification Mail',
                'Please verify the mail id by clicking on the below link http:localhost:8000/Professor/verify/'+str(instance.c_verification),
                
                
            )'''
            return render(request, 'Professor/verifymail.html')
        else:
            status = 422
    else:
        form=Postform()
    return render(request, 'Professor/tempform.html', {'form':form},status=status)
def view_home(request):
    if request.session.has_key('username') and request.session.has_key('type'):
        user = request.session['username']
        type = request.session['type']
        if (type == "student"):
            return render(request, 'student/loggedin.html', {'username': user})
        else:
            return render(request, 'Professor/loggedin.html', {'username': user})
    else:
        if request.method == 'POST':
            form=Loginform(data=request.POST)
            #print (form.errors)
            #print (form.non_field_errors)
            if form.is_valid():
                print("Validation Success")
                user=request.POST['username']
                passw=request.POST['password']
                try:
                    r=Register.objects.filter(c_name__exact=user)
                    if r.filter(c_password__exact=passw):
                        if r.values()[0]['c_verified'] :
                            request.session['username'] = user
                            request.session['type'] = "professor"
                            request.session.set_expiry(3000)
                            #form = EditForm()
                            return render(request,'Professor/loggedin.html',{'username':user})
                        else:
                            return render(request,'Professor/verifymail.html')
                    else:
                        return render(request, 'Professor/login_failure.html')
                except:
                    return render(request,'Professor/login_failure.html')
                #instance.save()
            else:
                print("Validation Failed")
                #form = Loginform()
                return render(request, 'Professor/login.html')
        else:
            form=Loginform()
            return render(request,'Professor/login.html',{'form':form})
#@login_required()
def view_edit(request):
    if request.session.has_key('username'):
        user = request.session["username"]
        if request.method == 'POST':
            print(user)
            tmp=Register.objects.get(c_name=user)
            print(tmp.c_professor_name,tmp.c_details)
            form=EditForm(request.POST,request.FILES,instance=tmp)
            print (form.errors)
            print (form.non_field_errors)
            if form.is_valid():
                instance = form.save(commit=False)
                # if instance.c_name!=instance.c_confirm_password:
                instance.save()
                #instance.save()
                return render(request,'Professor/Professorform.html',{'form':form, 'username':user})
            else:
                print("Validation Failed")
                #form = Loginform()
                return render(request, 'Professor/Professorform.html',{'form':form,'username':user})
        else:
            form = EditForm()
            return render(request,'Professor/Professorform.html',{'form':form,'username':user})
    else:
        return HttpResponse("Unauthorised Access")
def verify(request):
    if request.method == 'GET':
        val=int(request.GET['value'])
        name=request.GET['name']
        #print(val,name)
        #print(type(val))
        r=Register.objects.filter(c_name=name)[0]
        print(r)
        if r.c_verification == val:
            print("Success")
            r.c_verified=True
            r.save()
        else:
            pass
        form = EditForm()
        return render(request, 'Professor/verificationsuccess.html', {'form': form})
def projectreqs(request):
    if request.session.has_key('username'):
        if request.method == 'POST':
            user=request.session["username"]
            m=Register.objects.get(c_name=user)
            tmp=project_desc.objects.create(register=m)
            form=projectReqs(request.POST,instance=tmp)
            print (form.errors)
            print (form.non_field_errors)
            if form.is_valid():
                instance = form.save(commit=False)
                # if instance.c_name!=instance.c_confirm_password:
                instance.save()
                #i=project_desc.objects.filter(c_position=instance.c_position).update(register=tmp.id)

                #instance.save()
                form=projectReqs()
                return render(request,'Professor/projectreqs.html',{'form':form})
            else:
                print("Validation Failed")
                #form = Loginform()
                return render(request, 'Professor/projectreqs.html',{'form':form})
        else:
            form = projectReqs()
            return render(request,'Professor/projectreqs.html',{'form':form})
    else:
        return HttpResponse("Unauthorised Access")


def profile(request,username):
    if request.session.has_key('username'):
        user=request.session['username']
        tmp=Register.objects.filter(c_name=user)
        form=tmp.values()[0]
        return render(request,'Professor/Professor_profile.html',{'username':user,'form': form})
    else:
        return HttpResponse('Unauthorised Access')

def change_password(request):
    if request.session.has_key('username'):
        user=request.session['username']
        return render(request,'Professor/change_password.html',{'username':user})
    else:
        return HttpResponse('Unauthorised Access')

def successfull_change(request):
    if request.session.has_key('username'):
        user=request.session['username']
        tmp=Register.objects.get(c_name=user)
        try:
            old=request.POST["piCurrPass"]
            print(old)
            print(tmp.c_password)
            if tmp.c_password==old:
                tmp.c_password=request.POST["piNewPass"]
                tmp.c_confirm_password=request.POST["piNewPass"]
                tmp.save(update_fields=['c_password','c_confirm_password'])
        except:
            return HttpResponse('Unauthorised Access')
        return render(request,'Professor/loggedin.html',{'username':user})
    else:
        return HttpResponse('Unauthorised Access')
def listproject(request):
    if request.session.has_key('username'):
        user = request.session['username']
        m=Register.objects.get(c_name=user)
        tmp= project_desc.objects.filter(register=m)
        form=list(tmp.values())
        print(form)
        return render(request, 'Professor/list_project.html', {'form':form,'username':user})
    else:
        return HttpResponse('Unauthorised Access')

def projectdesc(request,projectid):
    #retrieve project description from database having id project id and give option to apply
    disable=""
    if request.session.has_key('username'):
        user = request.session['username']
        request.session['projectid'] = projectid
    else:
        user="Guest"
        disable="disabled"

    tmp=project_desc.objects.filter(pk=projectid)
    t=project_desc.objects.get(pk=projectid)
    form=list(tmp.values())#retrieved row
    name = Register.objects.get(pk=t.register_id).c_name
    return render(request, 'Professor/apply_project.html', {'form':form,'professor':name,'projectid':projectid,'username':user,'disabled':disable})

def projectapplied(request):
    #store student Id to applied, display a student profile page
    if request.session.has_key('projectid') and request.session.has_key('username'):
        projectid=request.session['projectid']
        user=request.session['username']
    else:
        projectid=1
        user="Guest"
    j=project_desc.objects.get(pk=projectid)
    if user in j.list_of_student.split(","):
        return HttpResponse("Already applied !!!")
    else:
        s=StudentDB.objects.get(s_username=user)
        a=Appliedproject(stdid=s,projectid=j)
        a.applied=True
        a.save()
        if(len(j.list_of_student)==0):
            j.list_of_student=user
        else:
            j.list_of_student=j.list_of_student+","+user
        j.save()
        return render(request, 'student/applied_msg.html')

def view_student_list(request,projectid):
    n=project_desc.objects.get(pk=projectid)
    stdnames=n.list_of_student.split(",")
    form=stdnames
    request.session['offerid']=projectid
    return render(request, 'Professor/student_list.html',{'form':form})

def already_taken(request):
    print ("here");
    if request.method == "GET":

professor/templates/Professor/Professor_profile.html
{% extends 'home/recruiter_profile.html' %}



{% block name %}
{{username}}
{% endblock %}

{%block main_body%}

<!--h1 class="page-header">Welcome {{username}}!!!</h1-->
<!--p class="">Originally authored by <a rel="nofollow" rel="noreferrer"href="http://bootsnipp.com/maridlcrmn">maridlcrmn</a> on Bootsnipp and then converted to Less and customized further by <a rel="nofollow" rel="noreferrer"href="http://twiter.com/j_holtslander">j_holtslander</a> who is building a <a rel="nofollow" rel="noreferrer"href="http://codepen.io/collection/nJGkWV" target="_new">collection</a> of great Bootstrap 3 navbars.</p-->
<div class="listing">
    <div class="form-group">
        <div class="">
            <span class="text-danger small">
                {{ form.errors }}
            </span>
        </div>
        <div class="">
            <div class="lead page-header">
            Professor Name
        </div>

            <div class="">{{ form.c_professor_name }}</div>
        </div>
        <div class="">
            <div class="lead page-header">

            Research Interests
            </div>
            <div class="">{{ form.c_details }}</div>
        </div>
        <div class="">
            <div class="lead page-header">
            Contact Details
            </div>
            <div class="">{{ form.c_email }}</div>
            <div class="">{{ form.c_contact }}</div>

        </div>
    </div>
</div>
{% endblock %}
<!--p>Click <a href ="{% url 'student:logout' %}">Here</a> To Logout</p-->

professor/templates/Professor/Professorform.html
{% extends 'home/recruiter_profile.html' %}

{% block title %}
    Change Password
{% endblock %}

{% block name %}
{{username}}
{% endblock %}


{% load bootstrap3 %}

{%block main_body%}
    <div style="background: rebeccapurple;">
    <div class="listing container-fluid">
    <h1>EDIT DETAILS!!!!</h1>
        <div style="color: black; vertical-align: middle;">
            <form  class="form-horizontal" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

            {% for field in form %}
        <div class="text-primary" style="vertical-align: middle;">
            <label class="text-primary">{{ field.label }}</label>
            {{ field }}
        </div>
    {% endfor %}
         <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-10">
        <button type="submit" class="btn btn-success">Submit</button>
                            </div>

         </div>
</form>
</div>
    </div>
</div>
{% endblock %}

professor/templates/Professor/apply_project.html
{% extends 'home/user_profile.html' %}
{% block name %}
{{username}}
{% endblock %}

{%block main_body%}

<div class="listing">
    {% for item in form %}
        <div class="lead page-header">Intern ID</div>
        <div>{{ item.id}}</div>
        <div class="lead page-header">Professor Name</div>
        <div>{{ professor }}</div>
        <div class="lead page-header">Intern Position</div>
        <div>{{ item.c_position }}</div>

        <div class="lead page-header">project Description</div>
        <div>{{ item.c_description }}</div>
        <div class="lead page-header">Stipend offered </div>
        <div>{{ item.c_ctc_offered }}</div>
        <div class="lead page-header">Degree Required</div>
        <div>{{ item.c_course }}</div>
        <div class="lead page-header">Branch Required</div>
        <div>{{ item.c_branch }}</div>
        <div>   <form class="form-horizontal " action="/Professor/applied_msg/{{ item.id }}" method="post" enctype="multipart/form-data">
                        <!--this is for security pupose against click jacking -->
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-10">
                                <button type="submit" class="btn btn-success" {{disabled}}>Apply</button>
                            </div>
                        </div>
                    </form>
        </div>
            {% endfor %}
</div>
{% endblock %}

professor/templates/Professor/change_password.html
{% extends 'home/recruiter_profile.html' %}

{% block title %}
    Change Password
{% endblock %}

{% block name %}
{{username}}
{% endblock %}

{%block main_body%}

<div class="container-fluid" style="background: rebeccapurple;">
<form class="form-horizontal" action="/Professor/changed" method="post">
    {% csrf_token %}
<fieldset>

<!-- Form Name -->
<legend class="text-primary">Change Password</legend>

<!-- Password input-->
<div class="form-group" >
  <label class="col-md-4 control-label text-primary" for="piCurrPass">Old Password</label>
  <div class="col-md-4">
    <input id="piCurrPass" name="piCurrPass" type="password" placeholder="" class="form-control input-md" required="">

  </div>
</div>

<!-- Password input-->
<div class="form-group">
  <label class="col-md-4 control-label text-primary"  for="piNewPass">New Password</label>
  <div class="col-md-4">
    <input id="piNewPass" name="piNewPass" type="password" placeholder="" class="form-control input-md" required="">

  </div>
</div>

<!-- Password input-->
<div class="form-group">
  <label class="col-md-4 control-label text-primary" for="piNewPassRepeat">Confirm New Password</label>
  <div class="col-md-4">
    <input id="piNewPassRepeat" name="piNewPassRepeat" type="password" placeholder="" class="form-control input-md" required="">

  </div>
</div>

<!-- Button (Double) -->
<div class="form-group">
  <label class="col-md-4 control-label" for="bCancel"></label>
  <div class="col-md-8">
    <button id="bGodkend" name="bGodkend" class="btn btn-success">Submit</button>
  </div>
</div>

</fieldset>
</form>
</div>
{% endblock %}

professor/templates/Professor/list_projects.html
{% extends 'home/recruiter_profile.html' %}
{%  block title %} Internship List Posted{% endblock %}
{% block name %}
{{username}}
{% endblock %}

{%block main_body%}

<div class="table-responsive listing">
<h1 class="page-header lead">Posted Intern List</h1>
    <table class="table table-bordered">
    <tr>
        <th>Intern ID</th>
        <th>Intern Position</th>
        <th>Professor ID</th>
        <th>Stipend offered </th>
        <th>Degree Required</th>
        <th>Branch Required</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Students Applied</th>
    </tr>
    {% for item in form %}
    <tr>
        <td>{{ item.id}}</td>
        <td>{{ item.c_position }}</td>
        <td>{{ item.register_id }}</td>
        <td>{{ item.c_stipend_offered }}</td>
        <td>{{ item.c_course }}</td>
        <td>{{ item.c_branch }}</td>
        <td>{{ item.date_published }}</td>
        <td>{{ item.date_expiry }}</td>
        <td><a href="/Professor/student_list/{{ item.id }}">View</a></td>

    </tr>
    {% endfor %}
</table>
</div>
{% endblock %}

professor/templates/Professor/loggedin.html
{% extends 'home/base.html' %}

{% block title %}Redirecting...{% endblock %}

{% block actives %}  {%endblock %}

{%block meta %}<meta http-equiv="refresh" content="2; url=/Professor/userc/{{username}}" /> {% endblock %}
{% block activec %} active {%endblock %}
{% load bootstrap3 %}

{% block body%}

<div id="backgroundImage">

<h2> hi {{ username }} logging in...</h2>
</div>
{%endblock%}

professor/templates/Professor/login.html
{% extends 'home/base.html' %}

{% block title %}RI_Portal:Professor{% endblock %}

{% block actives %}  {%endblock %}

{% block activec %} active {%endblock %}

{% block body%}
<div id="backgroundImage">


    <div class="container-fluid">
        <div class="row modal-body">
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2 class="heading col-sm-offset-2"><strong>Professor Login</strong></h2>
                    <br>
                    <form class="form-horizontal " action="" method="post" enctype="multipart/form-data">
                        <!--this is for security pupose against click jacking -->
                        {% csrf_token %}
                        {{ form }}

                        <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-10">
                                <button type="submit" class="btn btn-success">Login</button>
                            </div>
                        </div>
                    </form>
                    <a href="{% url 'Professor:signup_page' %}">New Professor Registration</a>

                </div>
            </div>
                </div>

            <div class="col-md-6">

            </div>
        </div>



    </div>


</div>
{% endblock %}

professor/templates/Professor/login_failure.html
{% extends 'home/base.html' %}

{% block title %}Redirecting...{% endblock %}
{% block meta %}
<meta http-equiv="refresh" content="1; url=/Professor/login/" />
{%endblock %}
{% block body%}

<div id="backgroundImage">


    <div class="container-fluid">
        <div class="row modal-body">
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2 class="" id="cursive"><strong>Invalid Login. Check Credentials</strong></h2>
                    <br>
                    <p>Redirecting to <a href ="/Professor/login">Home Page </a></p>
                </div>
            </div>
            </div>

          </div>
    </div>

</div>
{% endblock %}

professor/templates/Professor/login_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>LOGIN SUCCESS</h1>
</body>
</html>

professor/templates/Professor/post_list.html
<!DOCTYPE html>

<html lang="en">
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <meta charset="UTF-8">
    <title>Working</title>
    <p>Hi there!</p>
    <p>It works!</p>
</head>
<body>

</body>
</html>

professor/templates/Professor/projectreqs.html
{% extends 'home/Professor_profile.html' %}

{% block title %}
    Add New Internship
{% endblock %}

{% block name %}
{{username}}
{% endblock %}

{% block main_body %}

<form  method="POST" enctype="multipart/form-data" style="color:#000000">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-default">Submit</button>
</form>
{% endblock %}

professor/templates/Professor/student_list.html
{% extends 'home/Professor_profile.html' %}
{%  block title %} project List Posted{% endblock %}
{% block name %}
{{username}}
{% endblock %}

{%block main_body%}

<div class="table-responsive listing">
    <table class="table table-bordered">
    <tr>
        <th>Students Applied</th>
        <th>Give Offer</th>
    </tr>
    {% for item in form %}
    <tr>
        <td><a href="/student/profile/{{ item }}">{{ item }}</a></td>
        <td>
         <form class="form-horizontal " action="/Professor/offered/{{ item }}/" method="get" enctype="multipart/form-data">
                        <!--this is for security pupose against click jacking -->

                            <div class="">
                                <button type="submit" class="btn btn-success">Selected</button>
                        </div>
                    </form>
        </td>
    </tr>
    {% endfor %}
</table>
</div>
{% endblock %}

professor/templates/Professor/tempform.html
{% extends 'home/base.html' %}

{% block title %}Professor:Register{% endblock %}
{% block javascript %}

    <script>
        function CheckId() {
            $.get('/Professor/taken_name/', {username: $('#id_c_name').val()},
                function (data) {
                    if (data == "True") {
                        $('#idval').html("You may use this ID");
                    } else {
                        $('#idval').html("Unavailable");
                    }
                });
        }
        function onChange() {
            //alert("here");
            $("#id_c_name").keyup(function () {
                CheckId()
            });
        }
        $(document).ready(onChange);

    </script>

{% endblock %}
{% block body%}
<div id="backgroundImage">


    <div class="container-fluid">
        <div class="row modal-body">
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2 class="heading col-sm-offset-2"><strong>New Professor Registration</strong></h2>
                    <br>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        <!--this is for security pupose against click jacking -->
                        {% csrf_token %}

                          <div class="text-primary container-fluid row" style="vertical-align: middle;">
                                    <div class="col-sm-3">
                                    </div>
                                    <div id="idval" class="col-sm-3 text-danger">
                                    </div>
                                </div>

                                             {% for field in form %}
        <div class="text-primary container-fluid row" style="vertical-align: middle;">
            <div class="col-sm-3">
            <label class="text-primary">{{ field.label }}</label>
                </div>
            <div class="col-sm-3">
            {{ field }}
        </div>
        </div>
    {% endfor %}


                        <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-10">

                                <button type="submit" class="btn btn-success">Register  {{ data }}</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
                </div>

            <div class="col-md-6">


            </div>
        </div>



    </div>

</div>
{% endblock %}